/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bingo_myjnilib_JniUtils */

#ifndef _Included_com_bingo_myjnilib_JniUtils
#define _Included_com_bingo_myjnilib_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bingo_myjnilib_JniUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bingo_myjnilib_JniUtils_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
